import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Navbar from "./components/Navbar";
import Marquee from "react-fast-marquee";
import Footer from "./components/footer";
import HomeCard from "./home/page";


const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html
      lang="en"  data-theme="light"
      className={`${geistSans.variable} ${geistMono.variable} h-full antialiased`}
    >
      <body className="min-h-full flex flex-col">
         <Marquee className="bg-pink-900 text-white">New Arrivals: The Silent Forest | Special Discount on Memberships...</Marquee>
        <Navbar></Navbar>
      
        {children}
         <HomeCard></HomeCard>
        <Footer></Footer>
        </body>
    </html>
  );
}
